Roles
UnicornGlobal/strong-lumen pull request #2
Opened 2017-12-13 09:36 UTC by fergusdixon

Added roles middleware

2017-12-13 10:12 UTC, darrynten requested changes
Looking great so far :D

2017-12-13 10:12 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +{
we also need `getRoles` to list all the roles in the system

2017-12-13 10:12 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +    {
This should be in the users controller

2017-12-13 10:12 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +        return response('OK', 200);
User controller

2017-12-13 10:12 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +        return response('OK', 200);
Again

2017-12-13 10:12 UTC, darrynten commented on app/Http/Middleware/RolesMiddleware.php
> +            if (Auth::user()->roles->count() != 0) {
`!==` _never_ `!=` (except for, like, 0.00001% of the time)

2017-12-13 10:12 UTC, darrynten commented on app/Http/Middleware/RolesMiddleware.php
> +            }
space between these 2 ifs

2017-12-13 10:12 UTC, darrynten commented on app/Role.php
> +        'active' => true //Roles are active on creation
No inline comments

2017-12-13 10:12 UTC, darrynten commented on database/migrations/2017_12_08_142555_add_roles_tables.php
> +            $table->boolean('active');
is_active

2017-12-13 10:12 UTC, darrynten commented on database/migrations/2017_12_08_142555_add_roles_tables.php
> +            $table->boolean('active');
`$table->boolean('active')->default(true)`

2017-12-13 10:12 UTC, darrynten commented on database/seeds/DatabaseSeeder.php
> +        $this->call(Roles::class);
Just `$this->call('Roles')`

2017-12-13 10:12 UTC, darrynten commented on database/seeds/Roles.php
> +        UserRole::create([
Space between these 2 creates

2017-12-13 10:12 UTC, darrynten commented on routes/web.php
> +
Extraneous newline

2017-12-13 10:12 UTC, darrynten commented on tests/app/Http/AuthControllerTest.php
> +            //'Debug-Token' => env('DEBUG_KEY'),
No commented out code

2017-12-13 10:12 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        //before adding admin role
space between `//` and comment

2017-12-13 10:12 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +
No newline

2017-12-13 10:12 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +//        $this->assertResponseStatus(401);
Remove

2017-12-13 10:12 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        //Only 1st role
Spaces on these comment markers

2017-12-13 10:13 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +{
and getUsersForRole

2017-12-15 08:48 UTC, darrynten requested changes
Looks good so far.

Some changes needed, as well as an update to the readme explaining things.

Lekker

2017-12-15 08:48 UTC, darrynten commented on .gitignore
> +composer.lock
This file should not be ignored

2017-12-15 08:48 UTC, darrynten commented on app/BaseModel.php
> +    use ValidationTrait;
Space between the use and the next function

2017-12-15 08:48 UTC, darrynten commented on app/BaseModel.php
> +        $class  = get_called_class();
AFAIK his isn't the correct way of making a copy of the class that's called.

Try `__CLASS__`

2017-12-15 08:48 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +    public function getUserForRole($name)
Users (plural)

2017-12-15 08:48 UTC, darrynten commented on app/Http/Middleware/RolesMiddleware.php
> +            if (Auth::user()->roles->count() !== 0) {
Shouldn't this be Auth::user()->roles->exists() (or similar)?

2017-12-15 08:48 UTC, darrynten commented on app/Http/Middleware/RolesMiddleware.php
> +            if (Auth::user()->roles->count() !== 0) {
Perhaps hasAnyRole([]) with an array of roles the method loops through and if the array is empty it checks all roles

2017-12-15 08:48 UTC, darrynten commented on app/Http/Middleware/RolesMiddleware.php
> +            $model = Role::loadRoleFromName($role);
Does the called method do all the validation?

2017-12-15 08:48 UTC, darrynten commented on database/migrations/2017_12_08_142555_add_roles_tables.php
> +            $table->boolean('is_active');
->default(true)

2017-12-15 08:48 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        //Fail
Comments need space after //

2017-12-15 08:48 UTC, darrynten commented on routes/web.php
> +        $router->post('/assignRole/{userId}/{role}', 'UserController@assignRole');
Params should be role then user

2017-12-15 08:48 UTC, darrynten commented on database/seeds/Roles.php
> +        Role::create([
You also need `system` and `user` roles

2017-12-15 08:48 UTC, darrynten commented on app/BaseModel.php
> +    public static function loadRoleFromName($name)
Please add  PHP docblocks to all methods

2017-12-15 09:00 UTC, fergusdixon commented on app/BaseModel.php
> +        $class  = get_called_class();
http://willi.am/blog/2011/09/05/get-called-class-name-in-php/

2017-12-15 09:04 UTC, fergusdixon commented on app/BaseModel.php
> +        $class  = get_called_class();
`__CLASS__` returns `BaseModel`

2017-12-15 09:54 UTC, fergusdixon commented on app/Http/Middleware/RolesMiddleware.php
> +            $model = Role::loadRoleFromName($role);
Yip

2017-12-16 10:34 UTC, darrynten requested changes

2017-12-16 10:34 UTC, darrynten commented on README.md
> +- `POST` `/roles/deactivate/{name}`
I left some notes in slack about the names of these routes

GET /roles/{name}/users
GET /roles/{name}
GET /roles

POST /roles/{name}
DELETE /roles/{name}
POST /roles/{name}/activate
POST /roles/{name}/deactivate

2017-12-16 10:34 UTC, darrynten commented on README.md
> +- `POST` `/roles/revokeRole/{role}/{userId}`
GET /users/{userId}/roles
POST /users/{userId}/roles/assign/{name}
POST /users/{userId}/roles/revoke/{name}

2017-12-16 10:34 UTC, darrynten commented on README.md
> +- `POST` `/roles/deactivate/{name}`
I'm also wondering if we should use the UUIDs here.

It's easy to change the url to assign to admin if you see an assign call uses a name. If it has a UUID there's no names to fiddle with.

Let's make these UUIDs instead of name based.

Devs can get the UUIDs from the GET /roles call

Name based is just too risky for something this sensitive

2017-12-16 10:34 UTC, darrynten commented on app/Http/Middleware/RolesMiddleware.php
> +
Unneeded newline

2017-12-16 10:34 UTC, darrynten commented on database/seeds/Roles.php
> +            'name' => 'admin',
System should be id 1.

It's very common to compromise and escalate user user id 1 as it's usually admin.

Making a really limited user that cannot login or do much as id 1 or with assigning role id 1 would make an attack that successfully escalates to user id 1 will leave the attacker with a gimped account or permission that can't do much.

2017-12-16 10:34 UTC, darrynten commented on database/seeds/Roles.php
> +        ]);
You can add a 4th role, developer

2017-12-16 10:34 UTC, darrynten commented on database/seeds/Roles.php
> +            'created_by' => 5,
These should be marked assigned and created by the system user

2017-12-16 10:34 UTC, darrynten commented on routes/web.php
> +        $router->post('/deactivate/{name}', 'RolesController@deactivateRole');
See notes above about the naming of these routes

2017-12-16 10:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertEquals('admin', $roles[0]->name);
Test assigning a role that doesn't exist

2017-12-16 10:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertResponseStatus(401);
Test revoking a role that doesn't exist

2017-12-16 10:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertEquals('intern', $roles[3]->name);
Test get roles for a user that is not an admin

2017-12-16 10:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertEquals('5FFA95F4-5EB4-46FB-94F1-F2B27254725B', $users[0]->_id);
Also test getting an empty role

2017-12-16 10:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertEquals('Role name invalid', $this->response->getContent());
Test create role that already exists

2017-12-16 10:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertEquals('Test', $this->response->getContent());
Test user having 1 active and 1 inactive, and routes with neither 1 or each, and both set

2017-12-16 10:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertEquals('Test', $this->response->getContent());
Neither, 1 of each, and having both **

2017-12-18 07:43 UTC, fergusdixon commented on README.md
> +- `POST` `/roles/deactivate/{name}`
Sounds much better

2017-12-18 13:28 UTC, fergusdixon commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertEquals('intern', $roles[3]->name);
It will fail because getRoles is under admin protection. Should it not be?

2017-12-18 13:30 UTC, fergusdixon commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->assertEquals('5FFA95F4-5EB4-46FB-94F1-F2B27254725B', $users[0]->_id);
get `/roles/` will return all roles

2017-12-18 14:34 UTC, darrynten requested changes

2017-12-18 14:34 UTC, darrynten commented on README.md
> +- `POST` `/users/{userId}/roles/revoke/{role}`
for consistency put `id` inside the `{}` on each of these as it's always id

2017-12-18 14:34 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +            $role->_id = Uuid::generate(4);
Uuid::generate(4)->string

2017-12-18 14:34 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +            return response()->json(['uuid' => (string)$role->_id]);
You can remove the `(string)` with the change above

2017-12-18 14:34 UTC, darrynten commented on database/migrations/2017_12_08_142555_add_roles_tables.php
> +        Schema::create('user_role', function (Blueprint $table) {
user_roles?

2017-12-18 14:34 UTC, darrynten commented on routes/web.php
> +
Unneeded newline

2017-12-18 14:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +
Unneeded newline

2017-12-18 14:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +            . $this->testUserId
`sprintf`, never `.` string concats

2017-12-18 14:34 UTC, darrynten commented on tests/app/Http/Middleware/RoleMiddlewareTest.php
> +        $this->actingAs(Auth::user())->get('/users/' . $this->testUserId . '/roles');
sprintf everywhere

2017-12-18 14:34 UTC, darrynten commented on app/Http/Controllers/RolesController.php
> +            return response()->json(['uuid' => (string)$role->_id]);
`_id` instead of `uuid`

2017-12-18 14:45 UTC, fergusdixon commented on database/migrations/2017_12_08_142555_add_roles_tables.php
> +        Schema::create('user_role', function (Blueprint $table) {
Getting very weird issues with regards to the way Eloquent implies tables, the classes are `User` and `Role` so it looks for `user_role` from what I can tell

2017-12-20 10:37 UTC, darrynten requested changes

2017-12-20 10:37 UTC, darrynten commented on README.md
> +- `POST` `/roles/{name}/activate`
These are {id} not name

2017-12-20 10:37 UTC, darrynten commented on app/BaseModel.php
> +        $classId = self::getIdFromUuid($uuid, $model);
You can remove the static and call `$this->getIdFromUuid` no need for it to be static

2017-12-20 10:37 UTC, darrynten commented on app/BaseModel.php
> +    private static function getIdFromUuid($uuid, $model)
Per above, remove the static

2017-12-20 10:37 UTC, darrynten commented on app/Http/Controllers/UserController.php
> +                . 'The suspicious action has been logged.');
Concat goes at the end of the previous line

2017-12-20 10:37 UTC, darrynten commented on app/Http/Middleware/RolesMiddleware.php
> +
Unneeded

2017-12-20 10:37 UTC, darrynten commented on database/seeds/Roles.php
> +        ]);
Please reorder this and the one above so it goes id 1, 2, 3

2017-12-20 10:37 UTC, darrynten commented on database/seeds/Roles.php
> +        UserRole::create([
Docblock/comment for something this obscure, no idea what it's doing :D

2017-12-20 14:09 UTC, darrynten commented on README.md
> +- `POST` `/users/{id}/roles/revoke/{role}`
`roleId`?

2017-12-20 14:11 UTC, fergusdixon commented on README.md
> +- `POST` `/users/{id}/roles/revoke/{role}`
Oops

2017-12-20 14:11 UTC, darrynten approved these changes
Looking fantastic

2017-12-20 14:13 UTC, merged